import type { ProductDetail } from "@/components/product-detail-card"

export const productDetails: ProductDetail[] = [
  {
    slug: "carne-barbacoa-1-5kg",
    name: "CARNE BARBACOA DESFIADA 1,5kg",
    price: "R$ 71",
    image: "/carne.webp",
    features: ["Carne bovina desfiada", "Cozimento lento", "Pronta para servir", "Congelada", "Rende até 15 porções de 100g"],
    applications: ["Tacos", "Burritos", "Nachos", "Hambúrgueres", "Pizzas", "Saladas"],
  },
  {
    slug: "carne-chili-beans-1-5kg",
    name: "CHILI BEANS 1,5KG",
    price: "R$ 49,00",
    image: "/carne.webp",
    features: ["Receita tradicional mexicana", "Carne bovina e feijão temperados", "Pronto para servir", "Congelado", "Rende até 15 porções de 100g"],
    applications: ["Nachos", "Tacos", "Burritos", "Batatas Fritas", "Pizzas"],
  },
  {
    slug: "carne-costelinha-1-5kg",
    name: "COSTELINHA DESFIADA 1,5KG",
    price: "R$ 57,00",
    image: "/costelinha.webp",
    features: ["Costelinha suína cozida lentamente ao molho barbecue", "Extremamente suculenta", "Pronta para servir", "Congelada", "Rende até 15 porções 100g"],
    applications: ["Tacos", "Burritos", "Sanduíches", "Hambúrgueres", "Nachos", "Pizzas"],
  },
  {
    slug: "chili-veg-1kg",
    name: "CHILI VEG 1KG",
    price: "R$ 22,00",
    image: "/embalagens.webp",
    features: ["Proteína vegetal sabor mexicano", "Levemente apimentado", "Pronto para servir", "Congelado", "Excelente opção vegetariana"],
    applications: ["Tacos", "Burritos", "Nachos", "Bowls", "Wraps", "Pizzas", "Saladas"],
  },
  {
    slug: "frango-desfiado-ao-molho-1-5kg",
    name: "FRANGO DESFIADO AO MOLHO 1,5KG",
    price: "R$ 59,00",
    image: "/carne-embalada.webp",
    features: ["Frango extremamente macio", "Molho especial de tomate e mostarda", "Pronto para servir", "Congelado", "Rende até 30 coxinhas recheadas"],
    applications: ["Tacos", "Burritos", "Sanduíches", "Batatas", "Wraps", "Coxinhas", "Pastéis", "Risoles", "Pastelão", "Recheios salgados em geral"],
  },
  {
    slug: "frijoles-refritos-1kg",
    name: "FRIJOLES REFRITOS 1KG",
    price: "R$ 16,80",
    image: "/produtos-congelados.webp",
    features: ["Feijão mexicano cremoso", "Receita tradicional", "Pronto para servir", "Congelado", "Alto rendimento"],
    applications: ["Nachos", "Tacos", "Burritos", "Tostadas", "Pratos Mexicanos"],
  },
  {
    slug: "base-arroz-mexicano-100g",
    name: "BASE ARROZ MEXICANO 100G",
    price: "R$ 4,60",
    image: "/produtos-congelados.webp",
    features: ["Preparo rápido", "Rende até 900g de arroz pronto", "Receita exclusiva Nacho Man", "Fácil padronização"],
    applications: ["Bowls", "Pratos Executivos", "Mexicanos", "Delivery"],
  },
  {
    slug: "frango-empanado-hot-10un",
    name: "FRANGO EMPANADO HOT",
    subtitle: "10 unidades • 120g cada",
    price: "R$ 44,00",
    image: "/produtos-congelados.webp",
    features: ["Crocante por fora", "Suculento por dentro", "Levemente picante", "Congelado"],
    applications: ["Porções", "Combos", "Lanches", "Delivery", "Burritos"],
  },
  {
    slug: "churros-palito-1kg",
    name: "CHURROS PALITO 1KG",
    price: "R$ 14,40",
    image: "/embalagens-2.webp",
    features: ["Formato ideal para porções", "Fácil preparo", "Só fritar e finalizar", "Congelado"],
    applications: ["Sobremesas", "Festas", "Food Service", "Delivery"],
  },
  {
    slug: "mini-churros-sem-recheio-1kg",
    name: "MINI CHURROS SEM RECHEIO 1KG",
    price: "R$ 14,40",
    image: "/embalagens-3.webp",
    features: ["Mini churros de 10cm", "Congelados", "Só fritar e rechear", "Excelente rentabilidade"],
    applications: ["Sobremesas", "Cafeterias", "Eventos", "Delivery"],
  },
  {
    slug: "salsa-jalapeno-200ml",
    name: "SALSA JALAPEÑO 200ML",
    price: "R$ 14,00",
    image: "/molhos.webp",
    features: ["Sabor intenso", "Levemente defumada", "Receita mexicana", "Pronta para uso"],
    applications: ["Tacos", "Nachos", "Hambúrgueres", "Batatas", "Porções"],
  },
  {
    slug: "salsa-jalapeno-2l",
    name: "SALSA JALAPEÑO 2L",
    price: "R$ 74,90",
    image: "/molhos.webp",
    features: ["Embalagem econômica", "Food Service", "Alto rendimento", "Pronta para uso"],
    applications: ["Restaurantes", "Hamburguerias", "Dark Kitchens", "Franquias"],
  },
  {
    slug: "salsa-ghost-pepper-200ml",
    name: "SALSA GHOST PEPPER 200ML",
    price: "R$ 16,50",
    image: "/molhos.webp",
    features: ["Extremamente picante", "Produzida com Ghost Pepper", "Para amantes de pimenta", "Pronta para uso"],
    applications: ["Hambúrgueres", "Tacos", "Porções", "Desafios gastronômicos"],
  },
  {
    slug: "salsa-hot-pickles-200ml",
    name: "SALSA HOT PICKLES 200ML",
    price: "R$ 14,00",
    image: "/molhos.webp",
    features: ["Agridoce e picante", "Sabor marcante de picles", "Pronta para uso", "Receita exclusiva"],
    applications: ["Hambúrgueres", "Hot Dogs", "Batatas", "Sanduíches"],
  },
  {
    slug: "salsa-hot-pickles-1l",
    name: "SALSA HOT PICKLES 1L",
    price: "R$ 34,80",
    image: "/molhos.webp",
    features: ["Versão econômica", "Alto rendimento", "Food Service", "Pronta para uso"],
    applications: ["Hamburguerias", "Lanchonetes", "Restaurantes"],
  },
  {
    slug: "salsa-negra-200ml",
    name: "SALSA NEGRA 200ML",
    price: "R$ 14,00",
    image: "/molhos.webp",
    features: ["Perfil defumado", "Sabor intenso", "Receita exclusiva", "Pronta para uso"],
    applications: ["Carnes", "Hambúrgueres", "Tacos", "Costelas"],
  },
  {
    slug: "salsa-habanero-pina-200ml",
    name: "SALSA HABANERO PIÑA 200ML",
    price: "R$ 12,00",
    image: "/molhos.webp",
    features: ["Abacaxi com habanero", "Agridoce e picante", "Sabor tropical", "Pronta para uso"],
    applications: ["Tacos", "Peixes", "Frango", "Hambúrgueres"],
  },
  {
    slug: "salsa-roja-1l",
    name: "SALSA ROJA 1L",
    price: "R$ 32,00",
    image: "/molhos.webp",
    features: ["Receita tradicional mexicana", "Equilíbrio perfeito de sabor", "Food Service", "Pronta para uso"],
    applications: ["Tacos", "Burritos", "Nachos", "Pratos Mexicanos"],
  },
  {
    slug: "salsa-sweet-chili-200ml",
    name: "MOLHO SWEET CHILI 200ML",
    price: "R$ 12,00",
    image: "/molhos.webp",
    features: ["Agridoce levemente picante", "Muito versátil", "Pronta para uso", "Alta aceitação"],
    applications: ["Frango", "Batatas", "Porções", "Hambúrgueres"],
  },
  {
    slug: "salsa-sweet-chili-2l",
    name: "MOLHO SWEET CHILI 2L",
    price: "R$ 39,50",
    image: "/molhos.webp",
    features: ["Versão profissional", "Alto rendimento", "Food Service", "Excelente custo-benefício"],
    applications: ["Restaurantes", "Hamburguerias", "Dark Kitchens"],
  },
  {
    slug: "salsa-verde-300ml",
    name: "SALSA VERDE 300ML",
    price: "R$ 14,90",
    image: "/molhos.webp",
    features: ["Receita mexicana tradicional", "Refrescante e levemente ácida", "Pronta para uso", "Muito versátil"],
    applications: ["Tacos", "Burritos", "Nachos", "Carnes"],
  },
  {
    slug: "salsa-verde-600ml",
    name: "SALSA VERDE 600ML",
    price: "R$ 21,90",
    image: "/molhos.webp",
    features: ["Embalagem econômica", "Alto rendimento", "Food Service", "Pronta para uso"],
    applications: ["Restaurantes", "Lanchonetes", "Franquias"],
  },
  {
    slug: "kit-base-bacon-mayo",
    name: "KIT BASE BACON MAYO",
    price: "R$ 25,00",
    image: "/embalagens.webp",
    features: ["Produza até 2 litros", "Receita exclusiva", "Fácil preparo", "Alta lucratividade"],
    applications: ["Hambúrgueres", "Batatas", "Sanduíches", "Porções"],
  },
  {
    slug: "kit-base-molho-chipotle",
    name: "KIT BASE CHIPOTLE",
    price: "R$ 19,00",
    image: "/embalagens-3.webp",
    features: ["Produza até 2 litros", "Sabor defumado mexicano", "Fácil preparo", "Excelente rendimento"],
    applications: ["Hambúrgueres", "Tacos", "Sanduíches", "Batatas"],
  },
  {
    slug: "chamoy-geleia-500g",
    name: "CHAMOY (GELEIA) 500G",
    price: "R$ 21,00",
    image: "/molhos.webp",
    features: ["Molho mexicano agridoce", "Levemente picante", "Ideal para drinks", "Também usado em sobremesas e frutas"],
    applications: ["Drinks", "Sorvetes", "Frutas (manga, laranja, abacaxi)", "Sobremesas"],
  },
  {
    slug: "acucar-especial-churros-500g",
    name: "AÇÚCAR ESPECIAL PARA CHURROS 500G",
    price: "R$ 7,00",
    image: "/embalagens-2.webp",
    features: ["Mistura pronta", "Sabor autêntico", "Fácil aplicação", "Padronização garantida"],
    applications: ["Churros", "Sonhos", "Rosquinhas"],
  },
  {
    slug: "sal-temperado-batata-500g",
    name: "SAL ESPECIAL PARA BATATA 500G",
    price: "R$ 12,00",
    image: "/embalagens.webp",
    features: ["Tempero exclusivo", "Alta aderência", "Sabor intenso", "Pronto para uso"],
    applications: ["Batata Frita", "Batata Rústica", "Porções"],
  },
  {
    slug: "sal-temperado-chips-500g",
    name: "SAL ESPECIAL PARA CHIPS 500G",
    price: "R$ 6,00",
    image: "/embalagens-3.webp",
    features: ["Tempero exclusivo", "Realça sabor", "Fácil aplicação", "Excelente rendimento"],
    applications: ["Chips", "Snacks", "Batatas"],
  },
  {
    slug: "tajin-250g",
    name: "TAJÍN 250G",
    price: "R$ 32,00",
    image: "/molhos.webp",
    features: ["Tempero mexicano original", "Toque cítrico e picante", "Muito versátil", "Alto rendimento"],
    applications: ["Frutas", "Drinks", "Batatas", "Milho", "Petiscos"],
  },
]

export const productDetailsBySlug = new Map(
  productDetails.map((product) => [product.slug, product])
)
